### ISSUE TITLE
Closed codelists are not validated in record packages that declare extensions

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/lib-cove-ocds#112]
[Example](https://standard.open-contracting.org/review/data/e11c6d33-a73e-4d22-a46d-cfec49d1813d)

To reproduce:

1. Take the [example record](https://raw.githubusercontent.com/open-contracting/sample-data/main/fictional-example/1.1/record/ocds-213czf-000-00001.json)
2. Declare the [additional contact points extension](https://extensions.open-contracting.org/en/extensions/additionalContactPoint/master/)
3. In the compiled release, change `initiationType` to 'abc' and `tender.status` to 'abc'
4. Check the data using the DRT. It reports no errors.

The issue applies to compiled and embedded releases, but not to linked releases.

Related to CRM-7263

**Comment by jpmckinney** [comment]
In fact, hardly anything is validated in record packages when using extensions.

That is because `items` was missing from this JSON path:

https://github.com/open-contracting/lib-cove-ocds/blob/19ed9b3f0e392e9341206c5296d79c4bcc6f1206/libcoveocds/schema.py#L223-L225

**Comment by jpmckinney** [comment]
FYI @yolile No record packages that used extensions would return any structural errors (except at the package level) since at least August 2020 (https://github.com/open-contracting/lib-cove-ocds/commit/388df456112c5c6277ede07cd93f67cd763cb8b6#diff-28e5f63f790bad3d4f5a9ae1446a567329ceb1fff9234109c2cb6b5c628a1d0b), and maybe earlier (I'm not going to dig through lib-cove history at this point).
