### ISSUE TITLE
Internal server error when definition in extension cannot be dereferenced

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/lib-cove-ocds#66]
[Example](https://standard.open-contracting.org/review/?source_url=http://public.eprocurement.systems/ocds/tenders/ocds-b3wdp1-MD-1591270250226)

The issue is that there is a [typo](https://github.com/eOCDS-Extensions/eOCDS-addressDetails/blob/master/release-schema.json#L13) in the extension's `release-schema.json` which means a definition cannot be dereferenced.

Can this information be passed back to the user in the form of an error message? e.g.

> Could not dereference #/definitions/AddressDetails in [Address Details extension](https://github.com/eOCDS-Extensions/eOCDS-addressDetails)

**Comment by jpmckinney** [comment]
Can reproduce:

```
{
  "version": "1.1",
  "extensions": [
    "https://gist.githubusercontent.com/jpmckinney/7376110b73c6313507d50a628f2e6f88/raw/9ef2b515c7f8915477e88128d4a38755cabb48c1/extension.json"
  ],
  "publishedDate": "2000-01-01T00:00:00Z",
  "publisher": {
    "name": "Acme Inc."
  },
  "uri": "https://example.com",
  "releases": [
    {
      "ocid": "ocds-1234567",
      "id": "ocds-1234567-1",
      "date": "2000-01-01T00:00:00Z",
      "tag": ["tender"],
      "initiationType": "tender",
      "unresolvable": "1"
    }
  ]
}
```

`RefResolutionError: Unresolvable JSON pointer: 'definitions/Unresolvable'`

The error is raised at different points, depending on whether the `"unresolvable"` field is included. If it is included, it's raised by `jsonschema`:

> Internal Server Error
> Something went wrong with your request. This could be due to a bug in the application and/or the data you supplied.

If it's not, it's raised by `deref_schema`, which catches jsonref.JsonRefError and sets `json_deref_error` (noting that this can make some logic errors hard to discover, since `deref_schema` can be called indirectly):

> JSON reference error
> We have detected a JSON reference error in the schema. This may be due to some extension trying to resolve non-existing references.
> Error message: Unresolvable JSON pointer: '/definitions/Unresolvable'
