### ISSUE TITLE
Only one schema defined in extension.json is applied

### ISSUE THREAD

**Issue by yolile** [open-contracting/lib-cove-ocds#68]
When an extension declaration has more that one item in the "schema" field, as in: https://github.com/open-contracting-extensions/ocds_api_extension/blob/master/extension.json the tool only takes one of them to apply the patch (in this case release-schema only not release-package-schema):
![image](https://user-images.githubusercontent.com/6834122/53488902-5e096b80-3a6e-11e9-84c8-c2d5a8c74e7e.png)
![image](https://user-images.githubusercontent.com/6834122/53488913-66fa3d00-3a6e-11e9-9099-a49233c00894.png)

**Comment by duncandewhurst** [comment]
This issue came up again when looking at Portugal's data, which uses the pagination (API) extension

**Comment by jpmckinney** [comment]
Since OCDS 1.2 will de-emphasize packages, I think the simplest solution is to not report additional fields at the package level.

**Comment by duncandewhurst** [comment]
Hmmm, I'm not sure not reporting additional fields at the package level at all is the right solution since a publisher might, either in error or intentionally, add fields there and it would be useful for helpdesk analysts to be alerted to those, at least in the JSON output from the DRT.

Since we've seen few examples of extensions to the package metadata and since we plan to merge the pagination extension, I'm happy with not fixing the bug - but I don't think we should remove the additional fields reporting altogether.

**Comment by jpmckinney** [comment]
Sounds good. We can close then as no change is anticipated.
