### ISSUE TITLE
Document output JSON format

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/lib-cove-ocds#87]
So that it's clearer how other tools can query the data, e.g. in Kingfisher Process.

**Comment by Bjwebb** [comment]
Where's best to write this up? Shall I just put it into the README?

**Comment by Bjwebb** [comment]
@jpmckinney Where's best to write this up? Shall I just put it into the README?

**Comment by jpmckinney** [comment]
Yup, readme is fine.

**Comment by Bjwebb** [comment]
I've made a start on this at https://github.com/open-contracting/lib-cove-ocds/blob/document-output-json-format/README.rst#output-json-format

@jpmckinney Does the general format look okay? (I still have a bunch of text to fill in.)

I did consider doing this with a json schema, but that seemed like more work without any obvious benefits in this case. It should be fairly straightforward to convert it if required though.

**Comment by Bjwebb** [comment]
PR is now ready for review at https://github.com/open-contracting/lib-cove-ocds/pull/93.

I've added descriptive text for everything except [releases_aggregates](https://github.com/open-contracting/lib-cove-ocds/blob/document-output-json-format/README.rst#releases_aggregates), because I think most of the property names are clear enough.

**Comment by duncandewhurst** [comment]
Closing since the PR is merged.
